/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "file.h"

int *
tohex_1_svc(int *argp, struct svc_req *rqstp)
{
	static int  result;

	printf("\nequivalent hex %x", *argp);
	int n = *argp;
	char hex[10];
	int digit;
	int i=0, len;
	while(n>0) {
		digit = n%16;
		if(digit < 10)
			hex[i++] = digit+48;
		else
			hex[i++] = digit+55;
		
		n/=16;
	}
	hex[i] = '\0';
	len = i;
	char final_hex[len];

	for(int j=0; j<len; j++)
	{
		final_hex[j] = hex[len-j-1];
	}
	
	result = (int)strtol(final_hex, NULL, 16);
	return &result;
}

int *
tooct_1_svc(int *argp, struct svc_req *rqstp)
{
	static int  result;
	printf("\nequivalent oct %o", *argp);
	int n = *argp;
	int oct = 0, digit;
	int i=1;
	while(n>0) {
		digit = n%8;
		oct += digit*i;
		i*=10;
		n/=8;
	}
	result = oct;
	printf("\noct %d", oct);
	return &result;
}
