/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "file.h"


void
hexoct_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	int  tohex_1_arg=15;
	int  *result_2;
	int  tooct_1_arg = 10;

#ifndef	DEBUG
	clnt = clnt_create (host, HEXOCT, HEXOCT_1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = tohex_1(&tohex_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else
		printf("\nhex number : %x", *result_1);
	result_2 = tooct_1(&tooct_1_arg, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else 
		printf("\noctal number : %d", *result_2);
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	hexoct_1 (host);
exit (0);
}
